from app.plots.ai.show_build_dataset import prepare_build_dataset_data
from app.plots.ai.show_train_eeg import prepare_train_eeg_data
from app.plots.ai.show_model_summary import prepare_model_summary_data